import { useState, useCallback } from 'react';
import { FormData } from '@/lib/launchpad/types';

export function useFormState() {
  const [formData, setFormData] = useState<FormData>({
    staffId: null,
    formType: 'New Hire',
    firstName: '',
    middleName: '',
    lastName: '',
    jobTitle: '',
    employmentStatus: '',
    ssn: '',
    dob: '',
    email: '',
    cellPhone: '',
    homeWorkPhone: '',
    fullAddress: '',
    emergencyName: '',
    relationship: '',
    primaryPhone: '',
    secondaryPhone: '',
    highestDegree: '',
    yearAwarded: '',
    major: '',
    licenseStatus: '',
    licenseExpDate: '',
    npiNumber: '',
    languages: '',
    specialtyAreas: '',
    certTypes: [],
    certNumber: '',
    certExpDate: '',
    cprUpload: null,
    certificateUpload: null,
    hasExistingCpr: false,
    hasExistingCertificate: false,
    existingCprFilename: null,
    existingCertificateFilename: null,
    bankName: '',
    accountName: '',
    accountNumber: '',
    routingNumber: '',
    accountType: '',
    payrollAuth: false,
    taxIdProfessional: '',
    officePhoneNumber: '',
    officePhoneExt: '',
    timeZone: '',
    startTime: '',
    endTime: '',
    locationName: '',
    locationDescription: '',
    facilityType: '',
    facilityNpiNumber: '',
    facilityName: '',
    facilityAddress: '',
    facilityAptUnit: '',
    facilityCountry: 'US',
    facilityCity: '',
    facilityState: '',
    facilityZipCode: '',
    taxonomyCode: '',
    billingNpiNumber: '',
    billingProviderName: '',
    billingAddress: '',
    billingAptUnit: '',
    billingCountry: 'US',
    billingCity: '',
    billingState: '',
    billingZipCode: '',
    hipaaAck: false,
    abuseAck: false,
    digitalSignature: '',
    signatureDate: '',
  });

  const updateField = useCallback((field: keyof FormData, value: any) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
  }, []);

  const overwriteForm = useCallback((next: FormData) => {
    setFormData(next);
  }, []);

  const resetForm = useCallback(() => {
    setFormData({
      staffId: null,
      formType: 'New Hire',
      firstName: '',
      middleName: '',
      lastName: '',
      jobTitle: '',
      employmentStatus: '',
      ssn: '',
      dob: '',
      email: '',
      cellPhone: '',
      homeWorkPhone: '',
      fullAddress: '',
      emergencyName: '',
      relationship: '',
      primaryPhone: '',
      secondaryPhone: '',
      highestDegree: '',
      yearAwarded: '',
      major: '',
      licenseStatus: '',
      licenseExpDate: '',
      npiNumber: '',
      languages: '',
      specialtyAreas: '',
      certTypes: [],
      certNumber: '',
      certExpDate: '',
      cprUpload: null,
      certificateUpload: null,
      hasExistingCpr: false,
      hasExistingCertificate: false,
      existingCprFilename: null,
      existingCertificateFilename: null,
      bankName: '',
      accountName: '',
      accountNumber: '',
      routingNumber: '',
      accountType: '',
      payrollAuth: false,
      taxIdProfessional: '',
      officePhoneNumber: '',
      officePhoneExt: '',
      timeZone: '',
      startTime: '',
      endTime: '',
      locationName: '',
      locationDescription: '',
      facilityType: '',
      facilityNpiNumber: '',
      facilityName: '',
      facilityAddress: '',
      facilityAptUnit: '',
      facilityCountry: 'US',
      facilityCity: '',
      facilityState: '',
      facilityZipCode: '',
      taxonomyCode: '',
      billingNpiNumber: '',
      billingProviderName: '',
      billingAddress: '',
      billingAptUnit: '',
      billingCountry: 'US',
      billingCity: '',
      billingState: '',
      billingZipCode: '',
      hipaaAck: false,
      abuseAck: false,
      digitalSignature: '',
      signatureDate: '',
    });
  }, []);

  return { formData, updateField, overwriteForm, resetForm };
}

