<?php
/**
 * Script to create the backend/drive_helper.php wrapper file
 * Run this once to create the wrapper, then it will prevent redeclaration errors
 */

$backendDir = __DIR__ . '/backend';
$backendHelperPath = $backendDir . '/drive_helper.php';
$localHelperPath = __DIR__ . '/drive_helper.php';

echo "Creating wrapper file...\n";

// Remove existing file if it exists (might be symlink or copy)
if (file_exists($backendHelperPath)) {
    if (is_link($backendHelperPath)) {
        unlink($backendHelperPath);
        echo "Removed existing symlink\n";
    } elseif (is_file($backendHelperPath)) {
        unlink($backendHelperPath);
        echo "Removed existing file\n";
    }
}

// Create backend directory if needed
if (!is_dir($backendDir)) {
    if (mkdir($backendDir, 0755, true)) {
        echo "Created backend directory\n";
    } else {
        die("Failed to create backend directory\n");
    }
}

// Create wrapper file
$wrapperContent = "<?php\n";
$wrapperContent .= "// Wrapper to prevent redeclaration of drive_helper functions\n";
$wrapperContent .= "// This file is created automatically for composer autoloader compatibility\n";
$wrapperContent .= "// DO NOT EDIT THIS FILE MANUALLY\n";
$wrapperContent .= "if (!function_exists('getGoogleDriveClient')) {\n";
$wrapperContent .= "    require_once __DIR__ . '/../drive_helper.php';\n";
$wrapperContent .= "}\n";

if (file_put_contents($backendHelperPath, $wrapperContent)) {
    echo "Wrapper file created successfully at: $backendHelperPath\n";
    echo "File size: " . filesize($backendHelperPath) . " bytes\n";
    echo "\nWrapper file contents:\n";
    echo "---\n";
    echo $wrapperContent;
    echo "---\n";
} else {
    die("Failed to create wrapper file\n");
}

