/**
 * Mirrors backend/rbac_helpers.php legacy fallback when permissions[] not on the client.
 */
import { PERM } from "@/lib/rbac-permission-keys";

const ALL_MAHAVERSE = [
  PERM.NAV_DASHBOARD,
  PERM.NAV_SCHEDULING,
  PERM.NAV_CLIENTS,
  PERM.NAV_STAFF,
  PERM.NAV_USERS,
  PERM.NAV_MASTER_DATA,
  PERM.NAV_MANAGE_DATA,
  PERM.NAV_REPORTS,
  PERM.NAV_LAUNCHPAD,
  PERM.NAV_BILLING,
  PERM.VIEW_DASHBOARD,
  PERM.VIEW_SCHEDULING,
  PERM.VIEW_CLIENTS,
  PERM.VIEW_STAFF,
  PERM.VIEW_USERS,
  PERM.VIEW_MASTER_DATA,
  PERM.VIEW_MANAGE_DATA,
  PERM.VIEW_REPORTS,
  PERM.VIEW_LAUNCHPAD,
  PERM.VIEW_BILLING,
  PERM.VIEW_DOMAINS,
  PERM.VIEW_PROGRAMS,
  PERM.VIEW_TARGETS,
  PERM.VIEW_PROMPTS,
  PERM.VIEW_PROVIDER,
  PERM.VIEW_PROVIDER_SERVICE_CODE,
  PERM.VIEW_SERVICE_CODE,
  PERM.VIEW_DIAGNOSIS,
  PERM.VIEW_LOCATIONS,
  PERM.VIEW_FACILITY_TYPES,
  PERM.VIEW_TREATMENT_TYPES,
  PERM.VIEW_DOCUMENT_TYPES,
  PERM.CLIENTS_READ,
  PERM.CLIENTS_WRITE,
  PERM.STAFF_READ,
  PERM.STAFF_WRITE,
  PERM.USERS_READ,
  PERM.USERS_WRITE,
  PERM.SCHEDULING_READ,
  PERM.SCHEDULING_WRITE,
  PERM.REPORTS_READ,
  PERM.REPORTS_WRITE,
  PERM.MASTER_DATA_READ,
  PERM.MASTER_DATA_WRITE,
  PERM.MANAGE_DATA_READ,
  PERM.MANAGE_DATA_WRITE,
  PERM.BILLING_READ,
  PERM.BILLING_WRITE,
];

export function legacyPermissionsForRole(role) {
  const r = String(role || "").toLowerCase();
  if (r === "admin") {
    return ALL_MAHAVERSE;
  }
  if (r === "parent") {
    return [PERM.NAV_DASHBOARD, PERM.VIEW_DASHBOARD];
  }
  if (r === "biller") {
    return [
      PERM.NAV_DASHBOARD,
      PERM.NAV_CLIENTS,
      PERM.NAV_BILLING,
      PERM.VIEW_DASHBOARD,
      PERM.VIEW_CLIENTS,
      PERM.VIEW_BILLING,
      PERM.CLIENTS_READ,
      PERM.CLIENTS_WRITE,
      PERM.BILLING_READ,
      PERM.BILLING_WRITE,
    ];
  }
  if (r === "bcba" || r === "rbt") {
    return [
      PERM.NAV_SCHEDULING,
      PERM.NAV_CLIENTS,
      PERM.NAV_LAUNCHPAD,
      PERM.NAV_STAFF,
      PERM.VIEW_SCHEDULING,
      PERM.VIEW_CLIENTS,
      PERM.VIEW_LAUNCHPAD,
      PERM.VIEW_STAFF,
      PERM.VIEW_DOMAINS,
      PERM.VIEW_PROGRAMS,
      PERM.VIEW_TARGETS,
      PERM.VIEW_PROMPTS,
      PERM.CLIENTS_READ,
      PERM.CLIENTS_WRITE,
      PERM.STAFF_READ,
      PERM.STAFF_WRITE,
      PERM.SCHEDULING_READ,
      PERM.SCHEDULING_WRITE,
      PERM.MASTER_DATA_READ,
      PERM.MANAGE_DATA_READ,
    ];
  }
  return legacyPermissionsForRole("rbt");
}
